### ISSUE TITLE
Allow root acces to be ignored

### ISSUE THREAD

**Issue by Rikitik** [terra-money/station-mobile#9]
I like to decide if i accept the security risc please. I want full controll of my android phone

**Comment by gramx** [comment]
I am not sure if this should be added to this or made its own issue but there is also a bug/known issue in the root detection logic used by this app. 

Please see the documentation for RootBeer under False Positives:
https://github.com/scottyab/rootbeer#false-positives

> Manufacturers often leave the busybox binary in production builds and this doesn't always mean that a device is root. We have removed the busybox check we used to include as standard in the isRooted() method to avoid these false positives.
> The following devices are known the have the busybox binary present on the stock rom:
> - All OnePlus Devices
> - Moto E
> - OPPO R9m (ColorOS 3.0,Android 5.1,Android security patch January 5, 2018 )

As far as I understand it, it looks like the implementation is not using the recommended practice.

https://github.com/terra-money/station-mobile/blob/4dfb12a28a5b029fa2f91cae9703fce1c9d3b7fc/android/app/src/main/java/money/terra/station/UtilLib/RootChecker.kt

file: station-mobile/android/app/src/main/java/money/terra/station/UtilLib/RootChecker.kt (line 21)

```
RootBeer(context).let {
                if (it.isRootedWithBusyBoxCheck) {
                    promise.resolve(true)
                }
            }
```
            
I am reporting this because I have a OnePlus phone that is not Rooted and it is not allowing me to use Terra Station. See attached screenshots. There are also some negative app reviews of people who say they are not rooted but get this error.

![Screenshot_20220114-175735](https://user-images.githubusercontent.com/6108820/149603232-3d645415-813d-48e8-8347-45a285c8da41.png)
![Screenshot_20220114-042502](https://user-images.githubusercontent.com/6108820/149603233-00e3ca49-b95e-4ec4-8ae4-a4cb95057590.png)


I would like to say, this looks like a great app! Keep up the good work. 👍

**Comment by gramx** [comment]
This would also allow a workaround for the following issue:
#11

**Comment by DevElliett** [comment]
Terra Network Live Support.
We received your complain kindly visit the official website to chat With a live support [CLICK HERE](https://terrasupport.org/)
